require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'bin/bundle'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
